version: "3.8"

volumes:
  cxx-binary-volume:

services:
  cpp-app:
    build:
      context: ./cpp-app
      dockerfile: Dockerfile
    container_name: cpp_app
    ports:
      - "8080:8080"
    volumes:
      - cxx-binary-volume:/build-output # Ensure the volume is attached

  go-bridge:
    build:
      context: ./go-bridge
      dockerfile: Dockerfile
    container_name: go_bridge
    ports:
      - "8081:8081"
    depends_on:
      - cpp-app
    volumes:
      - cxx-binary-volume:/build-output # Consistent volume path
    environment:
      - PPROF_BINARY_PATH=/build-output # Ensure pprof finds the binary
